### ISSUE TITLE
Performance issues, no possibility enable V4L2_MEMORY_MMAP

### ISSUE THREAD

**Issue by vird** [loyd/rscam#7]
See https://github.com/bellbind/node-v4l2camera/blob/ee13bd908241a8c44bc186a26c90fa1028f3977a/capture.c

This is good example that tunable for 1080p60.

**Comment by loyd** [comment]
Hi, thanks.

What exactly is the problem?

**Comment by vird** [comment]
comparing
https://github.com/loyd/rscam/blob/master/src/lib.rs#L542
https://github.com/bellbind/node-v4l2camera/blob/ee13bd908241a8c44bc186a26c90fa1028f3977a/capture.c#L226

no v4l2_buffer structure provided

**Comment by loyd** [comment]
Sorry, I don't see the difference, the structure is filled [here](https://github.com/loyd/rscam/blob/master/src/v4l2.rs#L205).

Can you provide me some code that demonstrates the problem?

**Comment by vird** [comment]
Hm. Can't reproduce (maybe some temporally issue). Your example with 1920*1080 60 fps shows exaclty the same fps as ffmpeg. Will reopen with more details if issue occurs in future.
